language: python

sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - sudo apt-get install -y -qq curl
  - sudo apt-get update
  - "pip install -r requirements.txt"

# command to run tests
script:
  - >-
    curl -H "Content-Type: application/json" -X POST -d '{"password":"password"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password > /dev/null

  - py.test --cov=flask_ogm tests/

services:
  - neo4j

after_success:
  - coveralls
