language: python

sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - >-
    $ curl -H "Content-Type: application/json" -X POST -d '{"password":"password"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password


# command to run tests
script: py.test --cov=flask_ogm tests/

services:
  - neo4j

after_success:
  - coveralls
